<<<<<<< HEAD

# Site settings

url: "https://panossakkos.github.io"

# If you're hosting your site at a Project repository on GitHub pages
# (https://yourusername.github.io/repository-name)
# and NOT your user repository (https://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"

baseurl: /personal-jekyll-theme

google-tracking-id: "UA-35880426-4"

# Forces https everywhere in your website, except when you serve it locally

force-https: True

#############
# HTML Head #
#############

author: "John Smith"
lang: "en"
title: "{ John Smith }"
favicon: "/img/favicon.ico"
description: "Blog and website of John Smith, blogging mainly for tech. Opinions expressed are mine."
keywords: "smith, jones, personal, jekyll, theme"

################
# Intro layout #
################

black-favicon: "/img/black-lab-glass.ico"
background-img: "../img/intro-bg.jpg"
me-img: "/img/jetpacktocat.png"

##############################
# Dynamic Text on the header #
##############################

dynamic-typing: True
shuffle: True	# Shuffle the lines.
loop: True
loop-count:	False # Set False for infinite loop, or set any number for finite loop.
type-speed:	10		# Default 10
start-delay: 200	# Default 200
delete-delay: 5000	# Default 5000
lines:			# You can add HTML Tags in the Text
  - text: "The lower you fall, the higher you'll fly."
  - text: "Where’s your will to be weird?"

########
# Blog #
########

post-preview-words: 96

paginate: 5

fb-share: True
twitter-share: True
reddit-share: True
disqus-shortname: "panossakkos"

###############
# Life Events #
###############

events:
  - image: "/img/career/spidertocat.png"
    date: "September 2013 - Today"
    description: "Saving the neighborhood!"
  - image: "/img/career/baracktocat.jpg"
    date: "September 2007 - August 2013"
    description: "Started coding"

# First image of the Career timeline
career-img: "/img/career/default.png"

##################
# Contact layout #
##################

email: "your@email.here"

##################
# Social Buttons #
##################

social:
  - title: "facebook"
    url: "https://facebook.com/"
  - title: "twitter"
    url: "https://twitter.com/"
  - title: "youtube"
    url: "https://youtube.com/"
  - title: "github"
    url: "https://github.com/PanosSakkos/personal-jekyll-theme"
  - title: "rss"
    url: "/feed.xml"

############
# 404 page #
############

404-img: "/img/labtocat.png"

################################################################################

# Tread carefully if you want to change the variables below this point!

# Navigation bar links
# Blog link in the blog and post pages will point to the blog.html#blog
# In the default page it will point to the preview of the last post

pages_list:
  About: 'about'
  Blog: 'blog'
  Career: 'career'
  Contact: 'contact'

# Pagination path
paginate_path: "blog/page:num"

# Enable minification SASS
sass:
  style: compressed

# Exclusion list from the generated _site
exclude: ["Rakefile", "LICENSE", "readme.markdown", "vendor"]

=======
# Site settings
author: "Andrew Blum"
url: "http://axblum.github.io"
title: "Andrew Blum"
description: "Blog and website of Andrew Blum, blogging mainly for tech. Opinions expressed are mine."
favicon: "/img/favicon.ico"
black-favicon: "/img/black-lab-glass.ico"
disqus-shortname: "andrewblum"

#collection
collections:
  projects:
    output: true

# Conversion
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
highlighter: pygments
# Navigation bar links
# Blog link in the blog and post pages will point to the blog.html#blog
# In the default page it will point to the preview of the last post

pages_list:
  About: 'about'
  Blog: 'blog'
  Projects: 'projects'
  Career: 'career'
  Contact: 'contact'

background-img: "/img/intro-bg.jpg"

# About variables

me-img: "/img/me.jpg"

# Blog variables

paginate: 15

paginate_path: "blog/page:num"

post-preview-words: 128

fb-share: False
twitter-share: False
reddit-share: False

# Career variables

events:
  - image: "/img/career/dev_bootcamp_logo.png"
    date: "August 2015 - Today"
    description: "Learning"
  - image: "/img/career/tcc_logo.png"
    date: "July 2012 - August 2015"
    description: "IT Guru/Systems Engineer/DEVOPS @ The Climate Corporation"
  - image: "/img/career/google.png"
    date: "August 2010 - July 2012"
    description: "Infomation Technology Resident @ Google"
  - image: "/img/career/rit.jpg"
    date: "September 2005 - 2009"
    description: "BS in Applied Networking and Systems Administration"


# First image of the Career timeline
career-img: "/img/career/default.gif"

# Social networks variables (many more available: facebook, flickr, dribbble, pinterest, instagram, tumblr etc.)
social:
  - title: "github"
    url: "https://github.com/axblum"
  - title: "linkedin"
    url: "http://linkedin.com/in/blumandrew"

404-img: "/img/labtocat.png"

# Exclusion list from the generated _site
exclude: ["Rakefile", "LICENSE", "readme.markdown", "vendor"]
>>>>>>> gh-pages
gems: [jekyll-paginate]
