# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Code Savagery
email: 
description: > # this means to ignore newlines until "baseurl:"
  1000 hours at Dev Bootcamp and Beyond
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://chrislsavage.com" # the base hostname & protocol for your site
twitter_username: chrislsavage
github_username:  chrislsavage

# Build settings
markdown: kramdown
